# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'lab-ios' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab-ios
  source 'https://github.com/CocoaPods/Specs.git'

end
